---
 - hosts: all
   tasks:
    - name: installing apache2 service and starting
      apt:
       name: apache2
       state: present

    - name: starting apache service
      service:
       name: apache2
       state: started 